### ISSUE TITLE
Changing how non-analyses work

### ISSUE THREAD

**Issue by atticusha** [eddieantonio/fst-lookup#16]
Could you make it so that non-analyzed strings return a `?` instead of an empty list?

Love,

Atticus

**Comment by eddieantonio** [comment]
I say no to this proposal for a few reasons:

 1. as a **general purpose transduction library**, `?` is a valid tranduction! So I have no reason to discredit it.
 2. an empty return is a clear indication that the string could not be transduced in any meaningful way.

Does this make sense?

**Comment by eddieantonio** [comment]
@atticusha, please do something like this:

```python
analyses = list(fst.analyze(...))
if not analyses:
    return ['+?']
```

I _hate_ this convention!

Closing as `wontfix`! 😂
